backend:
  name: github
  repo: Andyming13/Glowon
  branch: main
  base_url: https://glowon-sms-oauth.vercel.app
  auth_endpoint: /api/auth

# ✅ 直接写主分支，不走草稿/PR（想走PR把 simple 改回 editorial_workflow）
publish_mode: simple

# ✅ 图片统一放这里；前端也按同路径读取
media_folder: "Archive/Untitled_design"
public_folder: "/Archive/Untitled_design"

locale: "zh_Hant"

collections:
  - label: "商品（Products）"
    name: "products"
    files:
      - label: "商品清單（products.json）"
        name: "products_json"
        file: "products.json"     # ✅ 以后只写根目录
        format: "json"
        fields:
          - label: "商品清單"
            name: "items"
            widget: "list"
            summary: "{{fields.title_zh}}（HKD {{fields.price_hkd}}）"
            fields:
              - {label: "ID（與圖片檔名一致，例如 28）", name: "id", widget: "string"}
              - {label: "分類", name: "category", widget: "select", options: ["instock","preorder","archived"], default: "instock"}
              - {label: "標題（繁中）", name: "title_zh", widget: "string"}
              - {label: "標題（EN）", name: "title_en", widget: "string"}
              - {label: "價格（HKD）", name: "price_hkd", widget: "number", value_type: "float", min: 0}
              # 留空時前端會用 Archive/Untitled_design/<id>.png
              - {label: "自定圖片（可留空）", name: "img", widget: "image", required: false}
              - {label: "描述（繁中）", name: "desc_zh", widget: "text", required: false}
              - {label: "描述（EN）", name: "desc_en", widget: "text", required: false}
