backend:
  name: github
  repo: Andyming13/Glowon
  branch: main
  base_url: https://glowon-sms-oauth.vercel.app   # ← 你在 Vercel 的网关域名

media_folder: "frontend/assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow
locale: "zh_Hant"

collections:
  - label: "商品（Products）"
    name: "products"
    files:
      - label: "商品清單（products.json）"
        name: "products_json"
        file: "frontend/products.json"
        format: "json"
        fields:
          - label: "商品清單"
            name: "items"
            widget: "list"
            summary: "{{fields.title_zh}}（HKD {{fields.price_hkd}}）"
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "分類", name: "category", widget: "select", options: ["instock","preorder","archived"], default: "instock"}
              - {label: "標題（繁中）", name: "title_zh", widget: "string"}
              - {label: "標題（EN）", name: "title_en", widget: "string"}
              - {label: "價格（HKD）", name: "price_hkd", widget: "number", value_type: "float", min: 0}
              - {label: "主圖（或多圖）", name: "img", widget: "image"}
              - {label: "描述（繁中）", name: "desc_zh", widget: "text", required: false}
              - {label: "描述（EN）", name: "desc_en", widget: "text", required: false}
